-- Assistant conversations: server-owned, durable chat history.
--
-- Owned by assistant-service. Until now the whole conversation lived in the
-- browser and was re-posted every turn, so a reload lost it and the client was
-- the source of truth for what had been said.
--
-- Three guarantees are carried by the schema itself rather than by code:
--   * ordering — messages are numbered per conversation, and the number is
--     unique, so two writers can never interleave a thread;
--   * no duplicate sends — the client's idempotency key is unique per
--     conversation, so a retried request collides instead of asking twice;
--   * no double execution — at most one pending write action per
--     conversation, claimed by an atomic status transition in code.

CREATE TABLE IF NOT EXISTS assistant_conversations (
  -- Generated by the client, so a retried first send cannot create a second
  -- conversation: the insert is ON CONFLICT DO NOTHING.
  id UUID PRIMARY KEY,
  organization_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  title VARCHAR(200),
  -- Also the per-conversation sequence counter: the next message takes
  -- message_count + 1, assigned only by the holder of the turn lease below.
  message_count INTEGER NOT NULL DEFAULT 0,
  -- Turn lease: one reply in progress per conversation, across tabs and
  -- service replicas. Expires, so a crashed turn cannot wedge the thread.
  active_turn_id UUID,
  turn_started_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT fk_assistant_conversations_organization
    FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_assistant_conversations_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- The history list: one user's live conversations, newest first, paged by
-- keyset on (last_message_at, id).
CREATE INDEX IF NOT EXISTS idx_assistant_conversations_owner_recent
  ON assistant_conversations(organization_id, user_id, last_message_at DESC, id DESC)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS assistant_messages (
  id BIGSERIAL PRIMARY KEY,
  conversation_id UUID NOT NULL,
  -- Denormalised so every read can be scoped without a join, and so the table
  -- can later be partitioned without reshaping queries.
  organization_id INTEGER NOT NULL,
  seq INTEGER NOT NULL,
  role VARCHAR(20) NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  -- An assistant message that called tools carries the calls; each tool result
  -- carries the id of the call it answers. Together they let a later turn
  -- replay what the model actually saw.
  tool_calls JSONB,
  tool_call_id VARCHAR(120),
  client_message_id UUID,
  -- 'failed' marks a user message whose turn errored, so the UI can offer a
  -- retry instead of showing a question that silently went unanswered.
  status VARCHAR(20) NOT NULL DEFAULT 'ok',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT assistant_messages_role_check
    CHECK (role IN ('user', 'assistant', 'tool')),
  CONSTRAINT assistant_messages_status_check
    CHECK (status IN ('ok', 'failed')),
  CONSTRAINT uq_assistant_messages_seq UNIQUE (conversation_id, seq),
  CONSTRAINT fk_assistant_messages_conversation
    FOREIGN KEY (conversation_id) REFERENCES assistant_conversations(id) ON DELETE CASCADE
);

-- Idempotency: a retried send carries the same key and collides here.
CREATE UNIQUE INDEX IF NOT EXISTS uq_assistant_messages_client_id
  ON assistant_messages(conversation_id, client_message_id)
  WHERE client_message_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS assistant_pending_actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL,
  organization_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  -- The model's tool call this action answers, so the result can be written
  -- back into the thread as that call's tool message.
  tool_call_id VARCHAR(120) NOT NULL,
  tool_name VARCHAR(100) NOT NULL,
  -- Executed from here, never from what the client sends back on confirm.
  arguments JSONB NOT NULL DEFAULT '{}'::jsonb,
  summary TEXT NOT NULL,
  destructive BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  result JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  decided_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '15 minutes'),
  CONSTRAINT assistant_pending_actions_status_check
    CHECK (status IN ('pending', 'executing', 'done', 'cancelled', 'expired', 'unknown')),
  CONSTRAINT fk_assistant_pending_actions_conversation
    FOREIGN KEY (conversation_id) REFERENCES assistant_conversations(id) ON DELETE CASCADE
);

-- At most one undecided write per conversation.
CREATE UNIQUE INDEX IF NOT EXISTS uq_assistant_pending_actions_open
  ON assistant_pending_actions(conversation_id)
  WHERE status IN ('pending', 'executing');
